### ISSUE TITLE
Language codes for bokmål and nynorsk

### ISSUE THREAD

**Issue by petterreinholdtsen** [piql/insight#15]
I noticed in the wip branch there was a comment claiming the 'no' language code refer to Norwegian Bokmål.  This is not quite accurate, as the 'no' language refer to Norwegian, which can be either Bokmål, Nynorsk og both.  The correct language code to use for Norwegian Bokmål is 'nb'.

Is there some technical reason, a legacy system perhaps, for using 'no' instead of 'nb'?

**Comment by oleliabo** [comment]
No you are correct, it is simply a mistake! The language files should be 'nb' instead of 'no'.

**Comment by oleliabo** [comment]
Fixed in latest release.
