### ISSUE TITLE
Very low userability on multiple N5 extractions

### ISSUE THREAD

**Issue by solfeggietto** [piql/insight#17]
As shown in attached screenshot with 3 imported N5 extractions from a  municipal:
I cannot find any way of closing the top level or any sublever categorization!

This makes it almost impossible to work on or hav openend more than 1 of them at the same time. The only way i could do this was endless scrolling up/down to find the root level cateogory and do a right click "Åpne = Open", also shown in the screenshot.

In addtion the 3rd open is very slow, now 32% after after 45 minutes, while opening this single exraction alone was matter of few minutes.

![kdrs-innsyn_insight_Issue_2020-01-29](https://user-images.githubusercontent.com/622856/73346251-d59ad880-4285-11ea-8146-4ef822a23340.png)

**Comment by solfeggietto** [comment]
Extraction 1 & 3 is already loaded, while the largest one Extraction 2 is very slow loading.
All 3 extraction was loaded individually, closing any existing extractions in insight beforehand.
All 3 extractions are full text indexed (which i need double check, a vaste number is reported as blank PDF, which is something we dont want it to report on PDF/A-1b with scan of image only, no text included in the PDF to read.

Extraction 1:
- arkivstruktur.xml = 149 MB
- Total tar size = 13 GB
- Documents = 37703 attachment located by insight

Extraction 2:
- arkivstruktur.xml = 274 MB
- Total tar size = 61 GB
- Documents = 73357 attachment located by insight

Extraction 3:
- arkivstruktur.xml = 12.4 MB
- Total tar size = 1.4 GB
- Documents = 2912 attachment located by insight

**Comment by oleliabo** [comment]
> As shown in attached screenshot with 3 imported N5 extractions from a municipal:
>I cannot find any way of closing the top level or any sublever categorization!

The current version disables collapse/expand on trees that has more than 200.000 nodes. The reason for this is that the underlying Qt tree component becomes very slow on large trees. I will test if this has improved in the latest version of Qt.

**Comment by oleliabo** [comment]
Limitation has been removed in latest version.
