### ISSUE TITLE
Confusing copyright and license status in source

### ISSUE THREAD

**Issue by petterreinholdtsen** [piql/insight#4]
The code include a LICENSE file with the GPL v3 terms, while the source files themselves include statements like this: "Copyright (c) 2017 Piql AS. All rights reserved."  "All rights reserved do not match the GPL terms.

Assuming the GPL terms are the wanted ones, it would be good to change the source files to instead have a statement like this:

```
Copyright (c) 2017 Piql AS.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

This would make it crystal clear which source files are GPL licenced.

**Comment by petterreinholdtsen** [comment]
Btw, probably best to change the http: to https: in the text.  Both work, though.

**Comment by oleliabo** [comment]
Yes, agree. Will fix this.

**Comment by oleliabo** [comment]
I have updated all the source files, so hopefully we are compliant now..

**Comment by petterreinholdtsen** [comment]
Jeg mistenker insight.pro også burde oppdateres.  Det var den eneste ikke-tredjepartsfilen jeg fant som fortsatt har 'All rights reserved'.
