### ISSUE TITLE
Document content indexing and search fail silently on Linux

### ISSUE THREAD

**Issue by petterreinholdtsen** [piql/insight#8]
The indexing of PDF content fail silently on Linux.  It would be better if such failure caused a popup notifying the user that the indexing failed.  I found this in reports/2019/11/5/174535/attachments.log:
```
Starting indexer: index.cmd ./reports/2019/11/5/174535/ ./reports/2019/11/5/174535/attachments/ i141ae7a1dd47e23362f600c1ac29228e
Failed to start: index.cmd ./reports/2019/11/5/174535/ ./reports/2019/11/5/174535/attachments/ i141ae7a1dd47e23362f600c1ac29228e
```

My system do not have index.cmd, and it is unclear where it is supposed to come from, as there is nothing in the git repository that seem relevant.  Missing file or dependency?

**Comment by oleliabo** [comment]
Yes, currently these resources are only available in the release zip file, they should be in the repo.

**Comment by petterreinholdtsen** [comment]
It would be useful to figure out how to do this on Linux, yes.  Are we talking about the Sphinx system available in Debian as https://tracker.debian.org/pkg/sphinxsearch ?

**Comment by oleliabo** [comment]
Yes, http://sphinxsearch.com

**Comment by oleliabo** [comment]
Error handling is improved in latest version, and the status bar at the bottom shows if the indexer failed. Closing for now.
